server:
  port: 8081


spring:
  application:
    name: order-svc
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/ordersvc
      username: pli
      password: 1234
      connectionTimeout: 5000
      validationTimeout: 1000
      maxinumPoolSize: 10

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    default-zone: http://localhost:8761/eureka